### PR TITLE
Support cases where CRS is not supported

### LINKED ISSUE #185: Running tests against a non CRS service results in test failure.
**Describe the bug**
We are using these excellent tests to test our OGC API Features service and use this as part of our build pipeline to ensure that our API conforms to the OGC API Features standard. Since the CRS tests have been added to this suite this is failing since we are not conforming to the CRS requirements class (https://docs.ogc.org/is/18-058/18-058.html). We have no plans to ever support CRS beyond the default https://www.opengis.net/def/crs/OGC/1.3/CRS84.

There already is functionality in the tests to enable/disable the tests depending on if the CRS requirements class is in the conformsTo section, however this test fails (so subsequent CRS tests are not executed) and it therefore looks like we are not passing the tests.

Is there a good way of disabling CRS tests - it looks like this is done automatically using the CrsRequirementClassPrecondition test, but that does result in one failed test.

**Workaround**
We could use a docker image that was built before CRS tests were applied, but that would limit us from any other improvements.

We could also just accept one failing test, but that sounds like that could hide a real bug in future.

**To Reproduce**
Run tests against a service that does not list CRS as a requirements class.

**Expected behavior**
CRS tests are skipped and no failurs are listed.

**Screenshots**
This is the resulting output of us running our tests:

<testng-results skipped="30" failed="1" total="106" passed="75">

**Additional context**
Thanks for this test suite, this is most excellent.

### PR DESCRIPTION
**Pull request by afasseco**
Hi

As mentioned here https://github.com/opengeospatial/ets-ogcapi-features10/issues/185 the tests fail if the service tested does not support CRS. As CRS support is not mandatory for a OGC API Feature service, then I think the CRS tests should be skipped. This way only if a service supports CRS the CRS tests will run.

Fixes #185.

Thanks.

### CODE REVIEW

**Comment by dstenger** [comment]
Thank you for providing the pull request.

This questing targets more in the direction how the test result is organized.
If you take a look at the HTML report, `Core` is listed under `Core conformance classes` which means that just this conformance class must be passed to get following result in the HTML report `Passed Core conformance classes (Implementations passing these classes can be certified): Yes`.
`Coordinate Reference Systems by Reference`, on the other hand, is not listed under `Core conformance classes` and thus not mandatory to get certified.

If you take the XML or EARL report, it is also possible to just consider the Core tests:
* XML: Just consider content of `<test name="Core">`.
* EARL: Check `/rdf:RDF/cite:TestRun/cite:areCoreConformanceClassesPassed`

I am more in favor of keeping the mechanism that the CRS tests fail as skipped tests could also mean pass/ no error.

I will discuss this in the CITE team and come back to you.

**Comment by afasseco** [comment]
Hi

I'm not exactly sure which html report you are referring to but the emailable-report.html report also shows the problem I'm facing:

Without change my service reports as:

image

With this change my service reports as:

image

Its the # failed I'm trying to avoid. In my opinion failed > 0 should mean that there is something wrong with the service.

I know that I can just ignore the CRS part and as stated in #185 a workaround could be to change the testng.xml.

**Comment by dstenger** [comment]
This is the report generated by TestNG. There is also a custom HTML report generated by TEAM Engine.
Still, the TestNG report states that 0 tests are failing for `Core`. Shouldn't that solve you use case?

Can you please describe which file you use in your integration test?

**Comment by afasseco** [comment]
We execute

java -cp '/usr/local/tomcat/webapps/teamengine/WEB-INF/lib/:/usr/local/tomcat/lib/' -DTE_BASE=config/ org.opengis.cite.ogcapifeatures10.TestNGController config/test-run-props.xml --generateHtmlReport true

and then do

grep -q "<testng-results.*failed=\"0\"" testng-results.xml

Which of course fails if failed is not 0 and since the service is compliant but does not implement CRS I do not think this is correct.

Usually we do not look at the html report - only if the above grep makes the pipeline fail then we look at the html report for what to correct (its usually pretty clear from the testng tests already).

I cannot see that I can find results from just the Core part - that does not seem to be in the testng-results.xml file.

**Comment by dstenger** [comment]
Discussion with CITE team:
The CITE team decided to accept the pull request as this mechanism is also fine for compliance certification.

**Comment by afasseco** [comment]
Thanks, that sounds good.

Looking forward to its release.

**Pull request merged**
