### PR TITLE
Support of relative server urls

### LINKED ISSUE #84: Relative path in server object of OpenAPI document leads to test failure
If the server object of the OpenAPI document contains a relative path in url element, following test fails:
```
validate Conformance Operation And Response
java.lang.IllegalStateException: Target host is null
```

However, when considering OpenAPI specification, relative paths in server objects are allowed: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#serverObject

So, the test suite must be adjusted to also accept relative paths in server object.

### PR DESCRIPTION
**Pull request by lgoltz**
Fixes #84

### CODE REVIEW

**Comment by dstenger** [comment]
Following service does not pass previously passed tests anymore.
https://services.interactive-instruments.de/t15/daraa
E.g.:

validate Feature Collections Metadata Operation Response_ Items | org.testng.SkipException: Could not find a response  for test point Server URL:  https://services.interactive-instruments.de/t15/daraa/api/                      , Path: /collections, Replacements: {}

validate Feature Collection Metadata Operation | java.lang.Throwable: Method  FeatureCollection.validateFeatureCollectionMetadataOperation(org.testng.ITestContext,  java.util.Map)<br>[pri:0,                       instance:org.opengis.cite.ogcapifeatures10.collections.FeatureCollection@5c99b014]  depends on not successfully finished methods                      in group "collections"

**Comment by cportele** [comment]
@dstenger - Is this an issue with the changes in the PR or do you think there is an issue with the API? If the latter, could you provide more detail, so that I can have a look (I see no problem in the server object or the path values).

**Comment by lgoltz** [comment]
The ETS requests the OpenAPI document as follows:

```
8d8cba> Request URI:	https://services.interactive-instruments.de/t15/daraa/api/
8d8cba> Proxy:			<none>
8d8cba> Request params:	<none>
8d8cba> Query params:	<none>
8d8cba> Form params:	<none>
8d8cba> Path params:	<none>
8d8cba> Headers:		Accept=application/vnd.oai.openapi+json;version=3.0
8d8cba> Cookies:		<none>
8d8cba> Multiparts:		<none>
8d8cba> Body:			<none>
8d8cba> Request method:	GET
```

The service returns 
```
 "servers" : [ {
    "url" : "https://services.interactive-instruments.de/t15/daraa/api/"
  } ]
```

The trailing '/' in the request url results to the unexpected server url, without this the expected server url is returned.

Trailing '/' was removed: https://github.com/opengeospatial/ets-ogcapi-features10/pull/90/commits/85383d7537940eee0c098633b6539f517b11bb1b

**Comment by dstenger** [comment]
Tested fix with several implementations and the expected result is returned now.

**Pull request merged**
