### PR TITLE
Fix test ConformanceTest

### PR DESCRIPTION
**Pull request by heidivanparys**
Fix test ConformanceTest by making it a JUnit test and updating the URIs
of the requirements classes.

### CODE REVIEW

**Comment by heidivanparys** [comment]
See also the first screenshot in #112 : test testParseAndValidateRequirementClasses fails.

**Comment by ghobona** [comment]
@heidivanparys There are two types of tests in the ETS.

Compliance tests: These are the executable tests that are implemented according to the specification of the abstract tests in the OGC standard.  They are implemented using TestNG in this Executable Test Suite.

Unit tests: These are integration tests that check whether the Compliance Tests are behaving as expected. Unit tests are implemented using junit.

The two types of tests are not interchangeable.

**Comment by ghobona** [comment]
@dstenger  Please note that the edits to [conformance/req-classes.json](https://github.com/opengeospatial/ets-ogcapi-features10/pull/113/files#diff-33cc6f106f765467a8ff31fc293e0df2) appear correct.

**Comment by ghobona** [comment]
@keshav-nangare Please review the PR as discussed today 2020-07-08

Conformance section in the spec is http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_response_3

**Comment by keshav-nangare** [comment]
@ghobona @dstenger 

I have tested this PR successfully.

**Pull request merged**
